#!/bin/bash

echo -e '\n'
echo -e "\e[1;33m                   "Checking Access point"                \e[0m"
 


if ping -c 2 ip > /dev/null ;then 
 echo  -e '\n' 
 echo  -e "\e[1;32m                   '1st floor AP working' \e[0m";
else 
 echo -e '\n'
 echo  -e "\e[1;31m                   '1st Ap Not-working' \e[0m";
fi
if ping -c 2 ip > /dev/null ;then 
 echo -e '\n'
 echo -e "\e[1;32m                   '2nd floor AP working' \e[0m";
else 
 echo -e '\n'
 echo -e "\e[1;31m                   '2nd floor Ap Not-working' \e[0m";
fi
if ping -c 2 ip> /dev/null ;then 
 echo -e '\n'
 echo -e "\e[1;32m                   'SJV AP working' \e[0m";
else 
 echo -e '\n'
 echo -e "\e[1;31m                   'SJV AP Not-working' \e[0m";
 
fi
echo -e '\n'





