#!/bin/bash
echo -n "enter user_name :"
read user_name
echo $user_name
#[ \$username > /dev/null ]
ldapsearch -LLL -D "domain/username" -w Password  -H  ldap://ip/domain-b dc=domain,dc=com "(sAMAccountName=$user_name)"
#echo $RESULt
  #echo "(test=`echo $c_c`)"

