#!/bin/bash

echo -----------------------
echo -n "enter source path":
read src
echo -e '\n'
echo -n "enter dest path":
read dest
echo -e '\n'
echo -n "enter system ip":
read ip
#echo -e '\n'
#echo -n "username":
#read user
 #scp /var/run/user/1000/gvfs/smb-share\:server\=ip\,share\=softwares/$src  username@$ip:/homeusername/$dest
#smbclient //ip/$src -U username/pass
#lcd /tmp
#recurse
#mget $dest


