#!/bin/bash

echo -e '\n\n'
echo -n " enter user name":
read userid
offset=$((134774*24*60*60))
echo $offset
lock=`ldapsearch -p 389   -h domain -D "username@domainname" -w password  '(sAMAccountName='$userid')' -LLL |grep lockout | column | cut -d ":" -f2`
expiry=`ldapsearch -p 389   -h domainname -D "username@domainname" -w password  '(sAMAccountName='$userid')' -LLL |grep pwdLast | column | cut -d ":" -f2`

#echo $expiry
echo $lock
echo $expiry
unixTimestamp=$((expiry/10000000-offset))
echo $unixTimestamp
#echo $unixTimestamp
echo -e '\n\n'
expr=$(date -d @"$unixTimestamp")
echo " Last Changed on------------- $expr-------------------"
#if [ $lock = "0"]then; print " unlocked"
#else 
#print " locked out"
echo -e '\n'

if [ $lock == "0" ]; then
echo "                               {{{{Account Is Active}}}}             "
else 
echo "                               {{{{Account Locked Out}}}}             "
fi
echo -e '\n\n'
#echo "              $lock              "


