#!/bin/bash

echo -e '\n\n'
echo -n " enter user name":
read userid
echo -n " enter user bindid":
read bindid
echo -n " enter user bindpass":
read -s   bindpass
echo -n " enter user domain":
read -s   domain
offset=$((134774*24*60*60))
echo -n "$offset"
lock=`ldapsearch -p 389   -h $domain -D "$bindid@$domain" -w $bindpass '(sAMAccountName='$userid')' -LLL |grep lockout | column | cut -d ":" -f2`
expiry=`ldapsearch -p 389   -h $domain -D "$bindid@$domain" -w $bindpass  '(sAMAccountName='$userid')' -LLL |grep pwdLast | column | cut -d ":" -f2`
#echo $expiry
echo -n "$lock"
echo -n "$expiry"
unixTimestamp=$((expiry/10000000-offset))
echo -n $unixTimestamp
#echo $unixTimestamp
echo -e '\n\n'
expr=$(date -d @"$unixTimestamp")
echo " Last Changed on------------- $expr-------------------"
#if [ $lock = "0"]then; print " unlocked"
#else 
#print " locked out"
echo -e '\n'

if [ $lock == "0" ]; then
echo "                               {{{{Account Is Active}}}}             "
else 
echo "                               {{{{Account Locked Out}}}}             "
fi
echo -e '\n\n'
#echo "              $lock              "


