#!/bin/bash
 
IF=$1
STAT=$2
 
if [ "$IF" == "wlan0" ];
then
    case "$2" in
        up)
        logger -s "NM Script up triggered"
         con=$(nmcli con status  | awk  '{print $1}' | tail -n 1)
         echo $con  >> /tmp/network.sh
         if [[ $con == "wifi" ]] || [[ $con == "wifi 1" ]] || [[ $con == "wifi 2" ]]; then
         #pwd
         #nmcli dev disconnect iface wlan0
         sudo notify-send -u   critical 'dmcmd'
         # if [[ $con == "wifi" ]] || [[ $con == "wifi 2" ]]; then
         #  notify-send  $con 
           else
           nmcli dev disconnect iface wlan0
         #  fi
         echo $con "?"  >> /tmp/network.sh
         echo " connecting to wifi" >>  /tmp/vtwork.sh
         echo "$(id)" >> /tmp/new.txt
         #nmcli con up iface wlan0 id Wifi
         #nmcli dev wifi connect Wifi
         fi
        ;;
        down)
        logger -s "NM Script down triggered"
        echo hellll >> /tmp/network.sh
        notify-send "diconnecting"
        ;;
        pre-up)
        logger -s "NM Script pre-up triggered"
        command3
        ;;
        post-down)
        logger -s "NM Script post-down triggered"
        command4
        ;;
        *)
        ;;
    esac
fi
