#!/bin/bash

echo -e '\n'
echo -e "\e[1;33m                   "Checking Printers"                \e[0m"
 


if ping -c 2 printer ip > /dev/null ;then 
 echo  -e '\n' 
 echo  -e "\e[1;32m                   '1st floor Printer working' \e[0m";
else 
 echo -e '\n'
 echo  -e "\e[1;31m                   '1st floor Printer working' \e[0m";
fi
if ping -c 2 printer ip > /dev/null ;then 
 echo -e '\n'
 echo -e "\e[1;32m                   '2nd floor Printer working' \e[0m";
else 
 echo -e '\n'
 echo -e "\e[1;31m                   '2nd floor Printer not working' \e[0m";
fi
echo -e '\n'
