#!/bin/bash

#echo $(dirname $0)
#if [ $(dirname $0)="home" ]then;
#   echo "home";
#fi;
echo $(dirname "$0")
if [ $(dirname $0) == "/home/username/Documents" ]; then
echo "home"
else 
echo "failed"
fi
